BEGIN
  FOR t IN (
    SELECT TABLE_NAME
    FROM USER_TABLES
    WHERE TABLE_NAME <> 'flyway_schema_history'
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "' || t.TABLE_NAME || '" CASCADE CONSTRAINTS';
  END LOOP;
END;
/
